### ISSUE TITLE
Setting when to perform garbage collection

### ISSUE THREAD

**Issue by geopast** [jdavidbakr/laravel-cache-garbage-collector#1]
Hi, i've installed this code to manage my cache size on www.pastpin.com. I'd like to set it to clear out say once a week - is that possible? Thanks :)

**Comment by jdavidbakr** [comment]
Yes, just add it to your console kernel schedule:

```
$schedule->command('cache:gc')
    ->weekly();
```

Of course you'll need to have the scheduler running as per https://laravel.com/docs/master/scheduling

**Comment by geopast** [comment]
Thanks!
