### ISSUE TITLE
Progress bar?

### ISSUE THREAD

**Issue by paulcdejean** [jdavidbakr/laravel-cache-garbage-collector#3]
I ran `php artisan cache:gc` in production and it's taking a very long time. Fortunately it doesn't seem to have brought down the server, but the resources are quite strained.

It's cleaning about a week's worth of garbage. Hopefully if I run this daily or hourly I'll have better results.

Is there any way to add some kind of progress indicator though for people that may run this in production?

**Comment by paulcdejean** [comment]
Ok it didn't take as long as I feared.

```
root@feature-production-10-0-219-72:/sites/master/current# setuser php php artisan cache:gc
Total expired cache files removed: 492314
Total active cache files remaining: 0
root@feature-production-10-0-219-72:/sites/master/current#
```

**Comment by jdavidbakr** [comment]
Yeah, it's designed to run in your scheduler to keep it clean, not really to run manually.

**Comment by paulcdejean** [comment]
Fair enough.
